baseURL = "https://data.adrianne.io/"
languageCode = "en-us"
title = "patterned.by.adrianne"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      autoHeadingID = true
    [markup.goldmark.extensions]
      typographer = true
      table = true
      strikethrough = true
      linkify = true

[menu]

  [[menu.main]]
  name = "Home"
  url = "/"
  pre = "<i class='fa-solid fa-house-chimney'></i> "
  weight = 1

[[menu.main]]
  name = "Work"
  url = "/work/"
  pre = "<i class='fa-solid fa-briefcase'></i> "
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  pre = "<i class='fa-solid fa-pen-nib'></i> "
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about/"
  pre = "<i class='fa-solid fa-user'></i> "
  weight = 4